### ISSUE TITLE
Add more resources links based on participant suggestions

### ISSUE THREAD

**Issue by GenevieveBuckley** [jni/lma-2021-bioimage-analysis-python#18]
Workshop participants put a whole bunch of great resources into the chat when we asked them about their favourite places to learn more about image analysis. 

We should add that information here too (most likely to the last section in the README, which currently contains a link to forum.image.sc and the napari zulip channel).

**Comment by GenevieveBuckley** [comment]
* https://forum.image.sc
* http://biii.eu/
* Freely available textbook "Bioimage data analysis workflows" by Kota Miura and Nataša Sladoje - https://link.springer.com/book/10.1007/978-3-030-22386-1
* NEUBIAS 
    * https://www.youtube.com/c/NEUBIAS/videos
    * http://eubias.org/NEUBIAS/training-schools/neubias-academy-home/
* https://github.com/guiwitz/neubias_academy_biapy
* https://www.simonwenkel.com/2019/07/19/list-of-annotation-tools-for-machine-learning-research.html


Someone else had a list here: https://forum.image.sc/t/bioimage-analysis-recommended-reading-and-viewing/28051

**Comment by GenevieveBuckley** [comment]
Hm, if this list gets long, perhaps we should put it in a separate markdown document and link that from the README and the 00 outline notebook.

**Comment by jni** [comment]
Within biii.eu, this page is not suuuuper intuitive to find, I'd link directly to it:

https://biii.eu/training-material

having said that, the other stuff on that page is 🏅!

Other than that, I think you have the full list @GenevieveBuckley!

I would just add these to the bottom of the README under "## further learning resources" "as suggested by workshop participants!"
