### ISSUE TITLE
Reword possibly misleading statement about dask

### ISSUE THREAD

**Issue by GenevieveBuckley** [jni/lma-2021-bioimage-analysis-python#3]
The dask tutorial includes this statement in the first couple of cells. I don't think this is strictly accurate, and it might be good to reword it.

> A first life hack: in general, avoid using bare dask, and instead create a dask.distributed Client as in the cell below. What this buys you:
>
> * memory management: the distributed scheduler that is automatically created with the default client will launch processes with maximum memory limits. If they exceed those limits, the scheduler will stop sending tasks to them and eventually kill them. In contrast, without distributed, you are subject to the same issues as bare Python. It is very easy to freeze your machine.

Dask documentation reference; https://docs.dask.org/en/latest/setup/single-distributed.html

**Comment by jni** [comment]
@GenevieveBuckley the docs page doesn't contradict the statement (?), but doesn't corroborate it either. I *think* when I wrote that I was speaking based on my experience (without the client, the tasks overflowed my RAM, with it they didn't), but maybe I muddled other factors in as well when I was trying stuff out.

**Comment by GenevieveBuckley** [comment]
It's not strictly incorrect, no. Mostly my brain keeps trying to interpret the meaning of that sentence to be "oh, so with distributed you get a scheduler, and without it you don't so tasks can overwhelm your machine". That is *not* what's actually written down, but it seems too easy for people to misunderstand. 

I'd like it to be clearer that when you run dask on a single machine without distributed, you get the threaded scheduler by default (and could choose the multiprocessing or synchronous scheduler too).

Point 3 on this documentation page seems like it's the reason you saw better handling of memory in your example. (I think it's reasonably likely you were doing something calling code which uses multiple processes) https://docs.dask.org/en/latest/scheduling.html

> 1. It provides access to asynchronous API, notably Futures
> 2. It provides a diagnostic dashboard that can provide valuable insight on performance and progress
> 3. It handles data locality with more sophistication, and so can be more efficient than the multiprocessing scheduler on workloads that require multiple processes
